import { z } from "zod";

const EventTypeBase = [
  "project_initialized",
  "rules_loaded",
  "rules_missing",
  "run_created",
  "run_started",
  "run_completed",
  "run_failed",
  "run_interrupted",
  "run_cancel_requested",
  "run_cancelled",
  "run_paused",
  "task_created",
  "task_started",
  "task_completed",
  "task_failed",
  "task_skipped",
  "task_interrupted",
  "context_pack_created",
  "executor_started",
  "executor_output",
  "executor_completed",
  "executor_exited",
  "executor_failed",
  "command_started",
  "command_completed",
  "command_failed",
  "command_blocked",
  "artifact_created",
  "validation_started",
  "validation_passed",
  "validation_failed",
  "approval_requested",
  "approval_approved",
  "approval_rejected",
  "quality_started",
  "quality_command_started",
  "quality_command_completed",
  "quality_command_failed",
  "quality_completed",
  "quality_failed",
  "resume_started",
  "resume_point_detected",
  "resume_task_marked_interrupted",
  "resume_continued",
  "resume_completed",
  "resume_failed",
  "retry_started",
  "retry_context_created",
  "retry_executor_started",
  "retry_validation_started",
  "retry_completed",
  "retry_failed",
  "retry_limit_reached",
  "process_started",
  "process_exited",
  "process_signal_sent",
  "process_stopped",
  "process_force_killed",
  "process_stale",
  "planner_fallback",
  "ai_planner_started",
  "ai_planner_output_received",
  "ai_planner_json_extracted",
  "ai_planner_validation_passed",
  "ai_planner_validation_failed",
  "ai_planner_repair_started",
  "ai_planner_repair_succeeded",
  "ai_planner_repair_failed",
  "ai_planner_fallback_to_simple",
  "internal_ai_planner_started",
  "internal_ai_planner_provider_selected",
  "internal_ai_planner_output_received",
  "internal_ai_planner_json_extracted",
  "internal_ai_planner_validation_passed",
  "internal_ai_planner_validation_failed",
  "internal_ai_planner_repair_started",
  "internal_ai_planner_repair_succeeded",
  "internal_ai_planner_repair_failed",
  "internal_ai_planner_fallback_to_simple",
  "ai_provider_stream_started",
  "ai_provider_stream_delta",
  "ai_provider_stream_completed",
  "ai_provider_stream_failed",
  "workflow_exported",
  "workflow_edited",
  "workflow_applied",
  "workflow_diff_shown",
  "workflow_added_task",
  "workflow_removed_task",
  "workflow_reordered",
  "workflow_replanned",
  "workflow_snapshot_saved",
  "prompt_detected",
  "prompt_input_provided",
  "prompt_cancelled",
  "prompt_timeout",
  "interactive_waiting",
  "interactive_resumed",
  "process_waiting_input",
  "error_occurred",
  "error_resolved",
  "error_recovery_attempted",
] as const;

export const EventTypeSchema = z.enum(EventTypeBase);

export const FlowTaskEventSchema = z.object({
  time: z.string().datetime(),
  type: EventTypeSchema,
  runId: z.string().optional(),
  taskId: z.string().optional(),
  message: z.string().optional(),
  details: z.record(z.unknown()).optional(),
});

export type FlowTaskEvent = z.infer<typeof FlowTaskEventSchema>;
export type EventType = z.infer<typeof EventTypeSchema>;

export const AuditActionSchema = z.enum([
  "workflow.create",
  "workflow.start",
  "workflow.pause",
  "workflow.resume",
  "workflow.cancel",
  "workflow.complete",
  "workflow.fail",
  "step.start",
  "step.complete",
  "step.fail",
  "step.skip",
  "step.retry",
  "step.approve",
  "step.deny",
  "step.block",
  "step.unblock",
  "approval.request",
  "approval.grant",
  "approval.deny",
  "approval.expire",
  "file.create",
  "file.modify",
  "file.delete",
  "file.rename",
  "artifact.create",
  "artifact.validate",
  "validation.pass",
  "validation.fail",
  "validation.skip",
  "config.change",
  "hook.execute",
  "hook.fail",
  "plugin.event",
  "error.occur",
  "error.resolve",
  "cost.limit",
  "token.limit",
  "user.input",
  "user.decision",
  "prompt.detected",
  "prompt.responded",
  "prompt.cancelled",
  "prompt.timeout",
  "process.input",
  "process.kill",
]);

export const AuditEventSchema = z.object({
  time: z.string().datetime(),
  action: AuditActionSchema,
  runId: z.string().optional(),
  taskId: z.string().optional(),
  stepId: z.string().optional(),
  actor: z.string().optional(),
  target: z.string().optional(),
  message: z.string().optional(),
  details: z.record(z.unknown()).optional(),
  severity: z.enum(["info", "warn", "error", "critical"]).default("info"),
});

export type AuditAction = z.infer<typeof AuditActionSchema>;
export type AuditEvent = z.infer<typeof AuditEventSchema>;

export const TimelineEntrySchema = z.object({
  timestamp: z.string().datetime(),
  type: z.string(),
  runId: z.string().optional(),
  taskId: z.string().optional(),
  stepId: z.string().optional(),
  status: z.string().optional(),
  message: z.string().optional(),
  details: z.record(z.unknown()).optional(),
});

export type TimelineEntry = z.infer<typeof TimelineEntrySchema>;
