import type { Task } from "../../schemas/task.schema.js";
import { generateTaskId } from "../../utils/ids.js";
import { now } from "../../utils/time.js";

export function generateFeatureTasks(runId: string, _prompt: string): Task[] {
  const timestamp = now();
  return [
    {
      id: generateTaskId(),
      runId,
      title: "Analyze requirements",
      description: "Review feature requirements and acceptance criteria.",
      status: "pending",
      executor: "shell",
      dependsOn: [],
      acceptanceCriteria: ["Requirements are documented"],
      retryCount: 0,
      maxRetries: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: generateTaskId(),
      runId,
      title: "Design implementation",
      description: "Design the feature architecture and component structure.",
      status: "pending",
      executor: "shell",
      dependsOn: [],
      acceptanceCriteria: ["Design document is created"],
      retryCount: 0,
      maxRetries: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: generateTaskId(),
      runId,
      title: "Implement feature",
      description: "Write the feature implementation code.",
      status: "pending",
      executor: "shell",
      dependsOn: [],
      acceptanceCriteria: ["Feature is implemented"],
      retryCount: 0,
      maxRetries: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: generateTaskId(),
      runId,
      title: "Add tests",
      description: "Write unit and integration tests for the feature.",
      status: "pending",
      executor: "shell",
      dependsOn: [],
      acceptanceCriteria: ["Tests are written and pass"],
      retryCount: 0,
      maxRetries: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: generateTaskId(),
      runId,
      title: "Run quality checks",
      description: "Verify typecheck, lint, and tests pass.",
      status: "pending",
      executor: "shell",
      dependsOn: [],
      acceptanceCriteria: ["All quality checks pass"],
      retryCount: 0,
      maxRetries: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ];
}
